# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
np.random.random((3,3,3))

array([[[0.81228447, 0.43399557, 0.30378287],
        [0.5095472 , 0.32329386, 0.3920048 ],
        [0.59268502, 0.62169852, 0.01360962]],

       [[0.52447879, 0.12760034, 0.82116903],
        [0.85566265, 0.22935359, 0.98301369],
        [0.10112305, 0.24256886, 0.81003923]],

       [[0.89399341, 0.6315633 , 0.29627934],
        [0.0747455 , 0.93184044, 0.27914783],
        [0.63691687, 0.45939371, 0.67965503]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.70474327  0.44186685  1.05298306  0.97518717  1.03789613]
 [-0.22665255  0.63721948 -1.07960452  0.39648359 -0.64659523]
 [-0.55487359 -0.31780121  0.49180943 -1.68764884  0.67783573]
 [ 0.48735715 -1.0627145  -1.66713891  0.12736946  1.35128248]
 [ 0.11023102  0.52557567 -1.82042635  1.24287046  1.2122313 ]]


# 5.  How to find common values between two arrays?

In [5]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 4 5 7 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

# 7. Consider two random array A and B, check if they are equal

In [7]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.4009877  0.20476684 0.07281602 0.01849762 0.919964   0.
 0.14983122 0.65511422 0.04036552 0.66163421]


# 9. How to print all the values of an array?

In [9]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.11586908  0.11331453 -0.09146605  0.43390507  0.02695687 -0.2656419
  -0.27958443 -0.25745811 -0.02381385  0.45965695]
 [ 0.04826136 -0.05847314  0.13214327 -0.24034391 -0.4620178   0.45266837
  -0.00104978 -0.34981811  0.31578799  0.16284176]
 [-0.47017973 -0.42099706  0.40002038  0.18351553  0.06965347  0.37243533
  -0.15913154 -0.01233964 -0.37423012  0.41125338]
 [-0.0140539   0.1443573   0.12753083  0.20162735 -0.35671405 -0.44204127
   0.39596614 -0.21806686 -0.34484562  0.50624007]
 [-0.29799847 -0.13858973 -0.16365594 -0.16821699  0.01536099  0.34221041
   0.62857766 -0.06311544 -0.23966094  0.08508845]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 4. 2. 3. 1. 2. 1. 3. 6. 6.]


In [12]:
np.add.at(Z, I, 1)
print(Z)

[ 3.  7.  3.  5.  1.  3.  1.  5. 11. 11.]


# 12.How to get the diagonal of a dot product?

In [13]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)

array([0.6749064 , 1.10983771, 0.61207232, 1.39887638, 1.05203148])

# 13.How to find the most frequent value in an array?

In [14]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


# 14.How to get the n largest values of an array

In [15]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [16]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
